version: '2'
services:
    jhipsterfileupload-app:
        image: jhipsterfileupload
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipsterfileupload-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterfileupload
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterfileupload-mongodb:
        extends:
            file: mongodb.yml
            service: jhipsterfileupload-mongodb
